// ============================================================================
// HD PRODUCTS LIST
// ----------------------------------------------------------------------------
// SOURCE OF TRUTH: image-pipeline/final_manifest.json (entries with hd: true).
//
// This file is GENERATED. Do not edit by hand. To add or remove an HD product,
// flip the `hd` flag on the manifest entry and re-run:
//   node scripts/generate-hd-products.js
// (also runs as part of `npm run prebuild`).
//
// Single source of truth for both the product catalog and the HD_BASE_IDS set
// — eliminates the historical drift where products[] and HD_BASE_IDS could
// silently diverge across commits.
// ============================================================================

export const HD_PRODUCTS = [
  // bookshelves-bright
  { id: 'bookshelves-bright-01-hd', name: "Bright Bookshelf #1", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-02-hd', name: "Bright Bookshelf #2", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-04-hd', name: "Bright Bookshelf #4", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-06-hd', name: "Bright Bookshelf #6", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-07-hd', name: "Bright Bookshelf #7", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-10-hd', name: "Bright Bookshelf #10", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-11-hd', name: "Bright Bookshelf #11", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-12-hd', name: "Bright Bookshelf #12", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-13-hd', name: "Bright Bookshelf #13", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-19-hd', name: "Bright Bookshelf #19", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-20-hd', name: "Bright Bookshelf #20", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-23-hd', name: "Bright Bookshelf #23", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-24-hd', name: "Bright Bookshelf #24", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-29-hd', name: "Bright Bookshelf #29", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-42-hd', name: "Bright Bookshelf #42", category: 'bookshelves-bright' },
  { id: 'bookshelves-bright-51-hd', name: "Bright Bookshelf #51", category: 'bookshelves-bright' },
  // bookshelves-dark
  { id: 'bookshelves-dark-02-hd', name: "Dark Bookshelf #2", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-06-hd', name: "Dark Bookshelf #6", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-07-hd', name: "Dark Bookshelf #7", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-08-hd', name: "Dark Bookshelf #8", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-09-hd', name: "Dark Bookshelf #9", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-23-hd', name: "Dark Bookshelf #23", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-25-hd', name: "Dark Bookshelf #25", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-27-hd', name: "Dark Bookshelf #27", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-28-hd', name: "Dark Bookshelf #28", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-37-hd', name: "Dark Bookshelf #37", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-40-hd', name: "Dark Bookshelf #40", category: 'bookshelves-dark' },
  { id: 'bookshelves-dark-41-hd', name: "Dark Bookshelf #41", category: 'bookshelves-dark' },
  // wall-shelves-bright
  { id: 'wall-shelves-bright-01-hd', name: "Bright Wall Shelf #1", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-02-hd', name: "Bright Wall Shelf #2", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-03-hd', name: "Bright Wall Shelf #3", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-05-hd', name: "Bright Wall Shelf #5", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-10-hd', name: "Bright Wall Shelf #10", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-12-hd', name: "Bright Wall Shelf #12", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-13-hd', name: "Bright Wall Shelf #13", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-16-hd', name: "Bright Wall Shelf #16", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-17-hd', name: "Bright Wall Shelf #17", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-20-hd', name: "Bright Wall Shelf #20", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-21-hd', name: "Bright Wall Shelf #21", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-28-hd', name: "Bright Wall Shelf #28", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-29-hd', name: "Bright Wall Shelf #29", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-49-hd', name: "Bright Wall Shelf #49", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-51-hd', name: "Bright Wall Shelf #51", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-54-hd', name: "Bright Wall Shelf #54", category: 'wall-shelves-bright' },
  { id: 'wall-shelves-bright-55-hd', name: "Bright Wall Shelf #55", category: 'wall-shelves-bright' },
  // wall-shelves-dark
  { id: 'wall-shelves-dark-01-hd', name: "Dark Wall Shelf #1", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-02-hd', name: "Dark Wall Shelf #2", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-04-hd', name: "Dark Wall Shelf #4", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-06-hd', name: "Dark Wall Shelf #6", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-17-hd', name: "Dark Wall Shelf #17", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-19-hd', name: "Dark Wall Shelf #19", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-26-hd', name: "Dark Wall Shelf #26", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-28-hd', name: "Dark Wall Shelf #28", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-29-hd', name: "Dark Wall Shelf #29", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-34-hd', name: "Dark Wall Shelf #34", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-42-hd', name: "Dark Wall Shelf #42", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-44-hd', name: "Dark Wall Shelf #44", category: 'wall-shelves-dark' },
  { id: 'wall-shelves-dark-51-hd', name: "Dark Wall Shelf #51", category: 'wall-shelves-dark' },
  // coffee-shops
  { id: 'coffee-shop-03-hd', name: "Coffee Shop #3", category: 'coffee-shops' },
  { id: 'coffee-shop-04-hd', name: "Coffee Shop #4", category: 'coffee-shops' },
  { id: 'coffee-shop-10-hd', name: "Coffee Shop #10", category: 'coffee-shops' },
  { id: 'coffee-shop-12-hd', name: "Coffee Shop #12", category: 'coffee-shops' },
  { id: 'coffee-shop-13-hd', name: "Coffee Shop #13", category: 'coffee-shops' },
  { id: 'coffee-shop-19-hd', name: "Coffee Shop #19", category: 'coffee-shops' },
  { id: 'coffee-shop-29-hd', name: "Coffee Shop #29", category: 'coffee-shops' },
  // conference-rooms
  { id: 'conference-room-01-hd', name: "Conference Room #1", category: 'conference-rooms' },
  { id: 'conference-room-02-hd', name: "Conference Room #2", category: 'conference-rooms' },
  { id: 'conference-room-03-hd', name: "Conference Room #3", category: 'conference-rooms' },
  { id: 'conference-room-04-hd', name: "Conference Room #4", category: 'conference-rooms' },
  { id: 'conference-room-05-hd', name: "Conference Room #5", category: 'conference-rooms' },
  { id: 'conference-room-06-hd', name: "Conference Room #6", category: 'conference-rooms' },
  { id: 'conference-room-21-hd', name: "Conference Room #21", category: 'conference-rooms' },
  { id: 'conference-room-22-hd', name: "Conference Room #22", category: 'conference-rooms' },
  // libraries
  { id: 'library-17-hd', name: "Library #17", category: 'libraries' },
  { id: 'library-33-hd', name: "Library #33", category: 'libraries' },
  { id: 'library-34-hd', name: "Library #34", category: 'libraries' },
  // urban-lofts
  { id: 'urban-loft-10-hd', name: "Urban Loft #10", category: 'urban-lofts' },
  { id: 'urban-loft-16-hd', name: "Urban Loft #16", category: 'urban-lofts' },
  { id: 'urban-loft-18-hd', name: "Urban Loft #18", category: 'urban-lofts' },
  { id: 'urban-loft-20-hd', name: "Urban Loft #20", category: 'urban-lofts' },
  { id: 'urban-loft-26-hd', name: "Urban Loft #26", category: 'urban-lofts' },
  { id: 'urban-loft-28-hd', name: "Urban Loft #28", category: 'urban-lofts' },
  { id: 'urban-loft-45-hd', name: "Urban Loft #45", category: 'urban-lofts' },
  // office-spaces
  { id: 'office-spaces-01-hd', name: "Office Space #1", category: 'office-spaces' },
  { id: 'office-spaces-02-hd', name: "Office Space #2", category: 'office-spaces' },
  { id: 'office-spaces-03-hd', name: "Office Space #3", category: 'office-spaces' },
  { id: 'office-spaces-05-hd', name: "Office Space #5", category: 'office-spaces' },
  { id: 'office-spaces-08-hd', name: "Office Space #8", category: 'office-spaces' },
  { id: 'office-spaces-10-hd', name: "Office Space #10", category: 'office-spaces' },
  { id: 'office-spaces-12-hd', name: "Office Space #12", category: 'office-spaces' },
  { id: 'office-spaces-15-hd', name: "Office Space #15", category: 'office-spaces' },
  { id: 'office-spaces-16-hd', name: "Office Space #16", category: 'office-spaces' },
  { id: 'office-spaces-19-hd', name: "Office Space #19", category: 'office-spaces' },
  { id: 'office-spaces-20-hd', name: "Office Space #20", category: 'office-spaces' },
  { id: 'office-spaces-24-hd', name: "Office Space #24", category: 'office-spaces' },
  { id: 'office-spaces-28-hd', name: "Office Space #28", category: 'office-spaces' },
  { id: 'office-spaces-33-hd', name: "Office Space #33", category: 'office-spaces' },
  { id: 'office-spaces-34-hd', name: "Office Space #34", category: 'office-spaces' },
  { id: 'office-spaces-35-hd', name: "Office Space #35", category: 'office-spaces' },
  { id: 'office-spaces-36-hd', name: "Office Space #36", category: 'office-spaces' },
  { id: 'office-spaces-38-hd', name: "Office Space #38", category: 'office-spaces' },
  { id: 'office-spaces-43-hd', name: "Office Space #43", category: 'office-spaces' },
  { id: 'office-spaces-59-hd', name: "Office Space #59", category: 'office-spaces' },
  { id: 'office-spaces-62-hd', name: "Office Space #62", category: 'office-spaces' },
  { id: 'office-spaces-63-hd', name: "Office Space #63", category: 'office-spaces' },
  { id: 'office-spaces-66-hd', name: "Office Space #66", category: 'office-spaces' },
  { id: 'office-spaces-69-hd', name: "Office Space #69", category: 'office-spaces' },
  { id: 'office-spaces-70-hd', name: "Office Space #70", category: 'office-spaces' },
  { id: 'office-spaces-71-hd', name: "Office Space #71", category: 'office-spaces' },
  { id: 'office-spaces-77-hd', name: "Office Space #77", category: 'office-spaces' },
  { id: 'office-spaces-84-hd', name: "Office Space #84", category: 'office-spaces' },
  { id: 'office-spaces-89-hd', name: "Office Space #89", category: 'office-spaces' },
  // home-office
  { id: 'home-offices-01-hd', name: "Home Office #1", category: 'home-office' },
  { id: 'home-offices-03-hd', name: "Home Office #3", category: 'home-office' },
  { id: 'home-offices-04-hd', name: "Home Office #4", category: 'home-office' },
  { id: 'home-offices-05-hd', name: "Home Office #5", category: 'home-office' },
  { id: 'home-offices-07-hd', name: "Home Office #7", category: 'home-office' },
  { id: 'home-offices-08-hd', name: "Home Office #8", category: 'home-office' },
  { id: 'home-offices-13-hd', name: "Home Office #13", category: 'home-office' },
  { id: 'home-offices-14-hd', name: "Home Office #14", category: 'home-office' },
  { id: 'home-offices-17-hd', name: "Home Office #17", category: 'home-office' },
  { id: 'home-offices-20-hd', name: "Home Office #20", category: 'home-office' },
  { id: 'home-offices-22-hd', name: "Home Office #22", category: 'home-office' },
  { id: 'home-offices-23-hd', name: "Home Office #23", category: 'home-office' },
  { id: 'home-offices-28-hd', name: "Home Office #28", category: 'home-office' },
  { id: 'home-offices-29-hd', name: "Home Office #29", category: 'home-office' },
  { id: 'home-offices-30-hd', name: "Home Office #30", category: 'home-office' },
  { id: 'home-offices-31-hd', name: "Home Office #31", category: 'home-office' },
  { id: 'home-offices-48-hd', name: "Home Office #48", category: 'home-office' },
  { id: 'home-offices-50-hd', name: "Home Office #50", category: 'home-office' },
  { id: 'home-offices-61-hd', name: "Home Office #61", category: 'home-office' },
  { id: 'home-offices-62-hd', name: "Home Office #62", category: 'home-office' },
  { id: 'home-offices-63-hd', name: "Home Office #63", category: 'home-office' },
  { id: 'home-offices-69-hd', name: "Home Office #69", category: 'home-office' },
  { id: 'home-offices-74-hd', name: "Home Office #74", category: 'home-office' },
  // nature-landscapes
  { id: 'nature-landscape-10-hd', name: "Nature Landscape #10", category: 'nature-landscapes' },
  { id: 'nature-landscape-11-hd', name: "Nature Landscape #11", category: 'nature-landscapes' },
  { id: 'nature-landscape-12-hd', name: "Nature Landscape #12", category: 'nature-landscapes' },
  { id: 'nature-landscape-14-hd', name: "Nature Landscape #14", category: 'nature-landscapes' },
  { id: 'nature-landscape-18-hd', name: "Nature Landscape #18", category: 'nature-landscapes' },
  { id: 'nature-landscape-19-hd', name: "Nature Landscape #19", category: 'nature-landscapes' },
  { id: 'nature-landscape-20-hd', name: "Nature Landscape #20", category: 'nature-landscapes' },
  { id: 'nature-landscape-21-hd', name: "Nature Landscape #21", category: 'nature-landscapes' },
  { id: 'nature-landscape-22-hd', name: "Nature Landscape #22", category: 'nature-landscapes' },
  { id: 'nature-landscape-30-hd', name: "Nature Landscape #30", category: 'nature-landscapes' },
  { id: 'nature-landscape-46-hd', name: "Nature Landscape #46", category: 'nature-landscapes' },
  { id: 'nature-landscape-98-hd', name: "Nature Landscape #98", category: 'nature-landscapes' },
  { id: 'nature-landscape-99-hd', name: "Nature Landscape #99", category: 'nature-landscapes' },
  // living-rooms
  { id: 'living-room-08-hd', name: "Living Room #8", category: 'living-rooms' },
  { id: 'living-room-10-hd', name: "Living Room #10", category: 'living-rooms' },
  { id: 'living-room-11-hd', name: "Living Room #11", category: 'living-rooms' },
  { id: 'living-room-14-hd', name: "Living Room #14", category: 'living-rooms' },
  { id: 'living-room-17-hd', name: "Living Room #17", category: 'living-rooms' },
  { id: 'living-room-27-hd', name: "Living Room #27", category: 'living-rooms' },
  { id: 'living-room-41-hd', name: "Living Room #41", category: 'living-rooms' },
  { id: 'living-room-46-hd', name: "Living Room #46", category: 'living-rooms' },
  // kitchens
  { id: 'kitchen-04-hd', name: "Kitchen #4", category: 'kitchens' },
  { id: 'kitchen-05-hd', name: "Kitchen #5", category: 'kitchens' },
  { id: 'kitchen-06-hd', name: "Kitchen #6", category: 'kitchens' },
  { id: 'kitchen-14-hd', name: "Kitchen #14", category: 'kitchens' },
  { id: 'kitchen-15-hd', name: "Kitchen #15", category: 'kitchens' },
  { id: 'kitchen-16-hd', name: "Kitchen #16", category: 'kitchens' },
  // gardens-patios
  { id: 'garden-patio-01-hd', name: "Garden & Patio #1", category: 'gardens-patios' },
  { id: 'garden-patio-12-hd', name: "Garden & Patio #12", category: 'gardens-patios' },
  { id: 'garden-patio-14-hd', name: "Garden & Patio #14", category: 'gardens-patios' },
  // christmas-backgrounds
  { id: 'christmas-background-35-hd', name: "Christmas #35", category: 'christmas-backgrounds' },
  // easter-backgrounds
  { id: 'easter-background-02-hd', name: "Easter #2", category: 'easter-backgrounds' },
  { id: 'easter-background-03-hd', name: "Easter #3", category: 'easter-backgrounds' },
  { id: 'easter-background-04-hd', name: "Easter #4", category: 'easter-backgrounds' },
  { id: 'easter-background-21-hd', name: "Easter #21", category: 'easter-backgrounds' },
  { id: 'easter-background-32-hd', name: "Easter #32", category: 'easter-backgrounds' },
  { id: 'easter-background-35-hd', name: "Easter #35", category: 'easter-backgrounds' },
  { id: 'easter-background-39-hd', name: "Easter #39", category: 'easter-backgrounds' },
  { id: 'easter-background-42-hd', name: "Easter #42", category: 'easter-backgrounds' },
  { id: 'easter-background-48-hd', name: "Easter #48", category: 'easter-backgrounds' },
  { id: 'easter-background-49-hd', name: "Easter #49", category: 'easter-backgrounds' },
  { id: 'easter-background-56-hd', name: "Easter #56", category: 'easter-backgrounds' },
  { id: 'easter-background-57-hd', name: "Easter #57", category: 'easter-backgrounds' },
  { id: 'easter-background-59-hd', name: "Easter #59", category: 'easter-backgrounds' },
  { id: 'easter-background-61-hd', name: "Easter #61", category: 'easter-backgrounds' },
  { id: 'easter-background-66-hd', name: "Easter #66", category: 'easter-backgrounds' },
  { id: 'easter-background-72-hd', name: "Easter #72", category: 'easter-backgrounds' },
  { id: 'easter-background-73-hd', name: "Easter #73", category: 'easter-backgrounds' },
  { id: 'easter-background-74-hd', name: "Easter #74", category: 'easter-backgrounds' },
  { id: 'easter-background-75-hd', name: "Easter #75", category: 'easter-backgrounds' },
  { id: 'easter-background-87-hd', name: "Easter #87", category: 'easter-backgrounds' },
  { id: 'easter-background-88-hd', name: "Easter #88", category: 'easter-backgrounds' },
  { id: 'easter-background-91-hd', name: "Easter #91", category: 'easter-backgrounds' },
  { id: 'easter-background-92-hd', name: "Easter #92", category: 'easter-backgrounds' },
  { id: 'easter-background-93-hd', name: "Easter #93", category: 'easter-backgrounds' },
  { id: 'easter-background-99-hd', name: "Easter #99", category: 'easter-backgrounds' },
  { id: 'easter-background-101-hd', name: "Easter #101", category: 'easter-backgrounds' },
  { id: 'easter-background-106-hd', name: "Easter #106", category: 'easter-backgrounds' },
  // spring-backgrounds
  { id: 'spring-background-01-hd', name: "Spring #1", category: 'spring-backgrounds' },
  { id: 'spring-background-36-hd', name: "Spring #36", category: 'spring-backgrounds' },
  { id: 'spring-background-43-hd', name: "Spring #43", category: 'spring-backgrounds' },
  { id: 'spring-background-55-hd', name: "Spring #55", category: 'spring-backgrounds' },
  { id: 'spring-background-63-hd', name: "Spring #63", category: 'spring-backgrounds' },
  { id: 'spring-background-73-hd', name: "Spring #73", category: 'spring-backgrounds' },
  { id: 'spring-background-74-hd', name: "Spring #74", category: 'spring-backgrounds' },
];

export const HD_BASE_IDS = new Set(HD_PRODUCTS.map((p) => p.slug || p.id.replace(/-hd$/, '')));
