// Single source of truth for all HD products.
// r2File is the literal key in the `streambackdrops-premium` R2/S3 bucket.
// Do NOT construct file paths anywhere else — always read product.r2File.

export const PRODUCTS = {
  // ── Bookshelves Bright ──────────────────────────────────────────────────────
  'bookshelves-bright-01-hd': { id: 'bookshelves-bright-01-hd', category: 'bookshelves-bright', index: 1,  title: 'Bright Bookshelf #1',  r2File: 'bookshelves-bright-01-hd.png' },
  'bookshelves-bright-02-hd': { id: 'bookshelves-bright-02-hd', category: 'bookshelves-bright', index: 2,  title: 'Bright Bookshelf #2',  r2File: 'bookshelves-bright-02-hd.png' },
  'bookshelves-bright-04-hd': { id: 'bookshelves-bright-04-hd', category: 'bookshelves-bright', index: 4,  title: 'Bright Bookshelf #4',  r2File: 'bookshelves-bright-04-hd.png' },
  'bookshelves-bright-06-hd': { id: 'bookshelves-bright-06-hd', category: 'bookshelves-bright', index: 6,  title: 'Bright Bookshelf #6',  r2File: 'bookshelves-bright-06-hd.png' },
  'bookshelves-bright-07-hd': { id: 'bookshelves-bright-07-hd', category: 'bookshelves-bright', index: 7,  title: 'Bright Bookshelf #7',  r2File: 'bookshelves-bright-07-hd.png' },
  'bookshelves-bright-10-hd': { id: 'bookshelves-bright-10-hd', category: 'bookshelves-bright', index: 10, title: 'Bright Bookshelf #10', r2File: 'bookshelves-bright-10-hd.png' },
  'bookshelves-bright-11-hd': { id: 'bookshelves-bright-11-hd', category: 'bookshelves-bright', index: 11, title: 'Bright Bookshelf #11', r2File: 'bookshelves-bright-11-hd.png' },
  'bookshelves-bright-13-hd': { id: 'bookshelves-bright-13-hd', category: 'bookshelves-bright', index: 13, title: 'Bright Bookshelf #13', r2File: 'bookshelves-bright-13-hd.png' },
  'bookshelves-bright-19-hd': { id: 'bookshelves-bright-19-hd', category: 'bookshelves-bright', index: 19, title: 'Bright Bookshelf #19', r2File: 'bookshelves-bright-19-hd.png' },
  'bookshelves-bright-20-hd': { id: 'bookshelves-bright-20-hd', category: 'bookshelves-bright', index: 20, title: 'Bright Bookshelf #20', r2File: 'bookshelves-bright-20-hd.png' },
  'bookshelves-bright-23-hd': { id: 'bookshelves-bright-23-hd', category: 'bookshelves-bright', index: 23, title: 'Bright Bookshelf #23', r2File: 'bookshelves-bright-23-hd.png' },
  'bookshelves-bright-24-hd': { id: 'bookshelves-bright-24-hd', category: 'bookshelves-bright', index: 24, title: 'Bright Bookshelf #24', r2File: 'bookshelves-bright-24-hd.png' },
  'bookshelves-bright-29-hd': { id: 'bookshelves-bright-29-hd', category: 'bookshelves-bright', index: 29, title: 'Bright Bookshelf #29', r2File: 'bookshelves-bright-29-hd.png' },
  'bookshelves-bright-42-hd': { id: 'bookshelves-bright-42-hd', category: 'bookshelves-bright', index: 42, title: 'Bright Bookshelf #42', r2File: 'bookshelves-bright-42-hd.png' },
  // ── Bookshelves Dark ───────────────────────────────────────────────────────
  'bookshelves-dark-02-hd': { id: 'bookshelves-dark-02-hd', category: 'bookshelves-dark', index: 2,  title: 'Dark Bookshelf #2',  r2File: 'bookshelves-dark-02-hd.png' },
  'bookshelves-dark-06-hd': { id: 'bookshelves-dark-06-hd', category: 'bookshelves-dark', index: 6,  title: 'Dark Bookshelf #6',  r2File: 'bookshelves-dark-06-hd.png' },
  'bookshelves-dark-07-hd': { id: 'bookshelves-dark-07-hd', category: 'bookshelves-dark', index: 7,  title: 'Dark Bookshelf #7',  r2File: 'bookshelves-dark-07-hd.png' },
  'bookshelves-dark-08-hd': { id: 'bookshelves-dark-08-hd', category: 'bookshelves-dark', index: 8,  title: 'Dark Bookshelf #8',  r2File: 'bookshelves-dark-08-hd.png' },
  'bookshelves-dark-09-hd': { id: 'bookshelves-dark-09-hd', category: 'bookshelves-dark', index: 9,  title: 'Dark Bookshelf #9',  r2File: 'bookshelves-dark-09-hd.png' },
  'bookshelves-dark-23-hd': { id: 'bookshelves-dark-23-hd', category: 'bookshelves-dark', index: 23, title: 'Dark Bookshelf #23', r2File: 'bookshelves-dark-23-hd.png' },
  'bookshelves-dark-25-hd': { id: 'bookshelves-dark-25-hd', category: 'bookshelves-dark', index: 25, title: 'Dark Bookshelf #25', r2File: 'bookshelves-dark-25-hd.png' },
  'bookshelves-dark-27-hd': { id: 'bookshelves-dark-27-hd', category: 'bookshelves-dark', index: 27, title: 'Dark Bookshelf #27', r2File: 'bookshelves-dark-27-hd.png' },
  'bookshelves-dark-28-hd': { id: 'bookshelves-dark-28-hd', category: 'bookshelves-dark', index: 28, title: 'Dark Bookshelf #28', r2File: 'bookshelves-dark-28-hd.png' },
  'bookshelves-dark-37-hd': { id: 'bookshelves-dark-37-hd', category: 'bookshelves-dark', index: 37, title: 'Dark Bookshelf #37', r2File: 'bookshelves-dark-37-hd.png' },
  // ── Wall Shelves Bright ────────────────────────────────────────────────────
  'wall-shelves-bright-01-hd': { id: 'wall-shelves-bright-01-hd', category: 'wall-shelves-bright', index: 1,  title: 'Bright Wall Shelf #1',  r2File: 'wall-shelves-bright-01-hd.png' },
  'wall-shelves-bright-02-hd': { id: 'wall-shelves-bright-02-hd', category: 'wall-shelves-bright', index: 2,  title: 'Bright Wall Shelf #2',  r2File: 'wall-shelves-bright-02-hd.png' },
  'wall-shelves-bright-03-hd': { id: 'wall-shelves-bright-03-hd', category: 'wall-shelves-bright', index: 3,  title: 'Bright Wall Shelf #3',  r2File: 'wall-shelves-bright-03-hd.png' },
  'wall-shelves-bright-05-hd': { id: 'wall-shelves-bright-05-hd', category: 'wall-shelves-bright', index: 5,  title: 'Bright Wall Shelf #5',  r2File: 'wall-shelves-bright-05-hd.png' },
  'wall-shelves-bright-10-hd': { id: 'wall-shelves-bright-10-hd', category: 'wall-shelves-bright', index: 10, title: 'Bright Wall Shelf #10', r2File: 'wall-shelves-bright-10-hd.png' },
  'wall-shelves-bright-13-hd': { id: 'wall-shelves-bright-13-hd', category: 'wall-shelves-bright', index: 13, title: 'Bright Wall Shelf #13', r2File: 'wall-shelves-bright-13-hd.png' },
  'wall-shelves-bright-16-hd': { id: 'wall-shelves-bright-16-hd', category: 'wall-shelves-bright', index: 16, title: 'Bright Wall Shelf #16', r2File: 'wall-shelves-bright-16-hd.png' },
  'wall-shelves-bright-17-hd': { id: 'wall-shelves-bright-17-hd', category: 'wall-shelves-bright', index: 17, title: 'Bright Wall Shelf #17', r2File: 'wall-shelves-bright-17-hd.png' },
  'wall-shelves-bright-20-hd': { id: 'wall-shelves-bright-20-hd', category: 'wall-shelves-bright', index: 20, title: 'Bright Wall Shelf #20', r2File: 'wall-shelves-bright-20-hd.png' },
  'wall-shelves-bright-28-hd': { id: 'wall-shelves-bright-28-hd', category: 'wall-shelves-bright', index: 28, title: 'Bright Wall Shelf #28', r2File: 'wall-shelves-bright-28-hd.png' },
  'wall-shelves-bright-29-hd': { id: 'wall-shelves-bright-29-hd', category: 'wall-shelves-bright', index: 29, title: 'Bright Wall Shelf #29', r2File: 'wall-shelves-bright-29-hd.png' },
  'wall-shelves-bright-49-hd': { id: 'wall-shelves-bright-49-hd', category: 'wall-shelves-bright', index: 49, title: 'Bright Wall Shelf #49', r2File: 'wall-shelves-bright-49-hd.png' },
  'wall-shelves-bright-51-hd': { id: 'wall-shelves-bright-51-hd', category: 'wall-shelves-bright', index: 51, title: 'Bright Wall Shelf #51', r2File: 'wall-shelves-bright-51-hd.png' },
  'wall-shelves-bright-54-hd': { id: 'wall-shelves-bright-54-hd', category: 'wall-shelves-bright', index: 54, title: 'Bright Wall Shelf #54', r2File: 'wall-shelves-bright-54-hd.png' },
  'wall-shelves-bright-55-hd': { id: 'wall-shelves-bright-55-hd', category: 'wall-shelves-bright', index: 55, title: 'Bright Wall Shelf #55', r2File: 'wall-shelves-bright-55-hd.png' },
  // ── Wall Shelves Dark ──────────────────────────────────────────────────────
  'wall-shelves-dark-01-hd': { id: 'wall-shelves-dark-01-hd', category: 'wall-shelves-dark', index: 1,  title: 'Dark Wall Shelf #1',  r2File: 'wall-shelves-dark-01-hd.png' },
  'wall-shelves-dark-02-hd': { id: 'wall-shelves-dark-02-hd', category: 'wall-shelves-dark', index: 2,  title: 'Dark Wall Shelf #2',  r2File: 'wall-shelves-dark-02-hd.png' },
  'wall-shelves-dark-04-hd': { id: 'wall-shelves-dark-04-hd', category: 'wall-shelves-dark', index: 4,  title: 'Dark Wall Shelf #4',  r2File: 'wall-shelves-dark-04-hd.png' },
  'wall-shelves-dark-06-hd': { id: 'wall-shelves-dark-06-hd', category: 'wall-shelves-dark', index: 6,  title: 'Dark Wall Shelf #6',  r2File: 'wall-shelves-dark-06-hd.png' },
  'wall-shelves-dark-17-hd': { id: 'wall-shelves-dark-17-hd', category: 'wall-shelves-dark', index: 17, title: 'Dark Wall Shelf #17', r2File: 'wall-shelves-dark-17-hd.png' },
  'wall-shelves-dark-19-hd': { id: 'wall-shelves-dark-19-hd', category: 'wall-shelves-dark', index: 19, title: 'Dark Wall Shelf #19', r2File: 'wall-shelves-dark-19-hd.png' },
  'wall-shelves-dark-28-hd': { id: 'wall-shelves-dark-28-hd', category: 'wall-shelves-dark', index: 28, title: 'Dark Wall Shelf #28', r2File: 'wall-shelves-dark-28-hd.png' },
  'wall-shelves-dark-29-hd': { id: 'wall-shelves-dark-29-hd', category: 'wall-shelves-dark', index: 29, title: 'Dark Wall Shelf #29', r2File: 'wall-shelves-dark-29-hd.png' },
  'wall-shelves-dark-34-hd': { id: 'wall-shelves-dark-34-hd', category: 'wall-shelves-dark', index: 34, title: 'Dark Wall Shelf #34', r2File: 'wall-shelves-dark-34-hd.png' },
  // ── Coffee Shops ──────────────────────────────────────────────────────────
  'coffee-shop-03-hd': { id: 'coffee-shop-03-hd', category: 'coffee-shops', index: 3,  title: 'Coffee Shop #3',  r2File: 'coffee-shop-03-hd.png' },
  'coffee-shop-04-hd': { id: 'coffee-shop-04-hd', category: 'coffee-shops', index: 4,  title: 'Coffee Shop #4',  r2File: 'coffee-shop-04-hd.png' },
  'coffee-shop-10-hd': { id: 'coffee-shop-10-hd', category: 'coffee-shops', index: 10, title: 'Coffee Shop #10', r2File: 'coffee-shop-10-hd.png' },
  'coffee-shop-12-hd': { id: 'coffee-shop-12-hd', category: 'coffee-shops', index: 12, title: 'Coffee Shop #12', r2File: 'coffee-shop-12-hd.png' },
  'coffee-shop-19-hd': { id: 'coffee-shop-19-hd', category: 'coffee-shops', index: 19, title: 'Coffee Shop #19', r2File: 'coffee-shop-19-hd.png' },
  // ── Conference Rooms ──────────────────────────────────────────────────────
  'conference-room-01-hd': { id: 'conference-room-01-hd', category: 'conference-rooms', index: 1, title: 'Conference Room #1', r2File: 'conference-room-01-hd.png' },
  'conference-room-02-hd': { id: 'conference-room-02-hd', category: 'conference-rooms', index: 2, title: 'Conference Room #2', r2File: 'conference-room-02-hd.png' },
  'conference-room-04-hd': { id: 'conference-room-04-hd', category: 'conference-rooms', index: 4, title: 'Conference Room #4', r2File: 'conference-room-04-hd.png' },
  'conference-room-05-hd': { id: 'conference-room-05-hd', category: 'conference-rooms', index: 5, title: 'Conference Room #5', r2File: 'conference-room-05-hd.png' },
  'conference-room-06-hd': { id: 'conference-room-06-hd', category: 'conference-rooms', index: 6, title: 'Conference Room #6', r2File: 'conference-room-06-hd.png' },
  // ── Libraries ─────────────────────────────────────────────────────────────
  'library-17-hd': { id: 'library-17-hd', category: 'libraries', index: 17, title: 'Library #17', r2File: 'library-17-hd.png' },
  'library-33-hd': { id: 'library-33-hd', category: 'libraries', index: 33, title: 'Library #33', r2File: 'library-33-hd.png' },
  'library-34-hd': { id: 'library-34-hd', category: 'libraries', index: 34, title: 'Library #34', r2File: 'library-34-hd.png' },
  // ── Urban Lofts ───────────────────────────────────────────────────────────
  'urban-loft-10-hd': { id: 'urban-loft-10-hd', category: 'urban-lofts', index: 10, title: 'Urban Loft #10', r2File: 'urban-loft-10-hd.png' },
  'urban-loft-18-hd': { id: 'urban-loft-18-hd', category: 'urban-lofts', index: 18, title: 'Urban Loft #18', r2File: 'urban-loft-18-hd.png' },
  'urban-loft-20-hd': { id: 'urban-loft-20-hd', category: 'urban-lofts', index: 20, title: 'Urban Loft #20', r2File: 'urban-loft-20-hd.png' },
  'urban-loft-26-hd': { id: 'urban-loft-26-hd', category: 'urban-lofts', index: 26, title: 'Urban Loft #26', r2File: 'urban-loft-26-hd.png' },
  'urban-loft-28-hd': { id: 'urban-loft-28-hd', category: 'urban-lofts', index: 28, title: 'Urban Loft #28', r2File: 'urban-loft-28-hd.png' },
  // ── Office Spaces ─────────────────────────────────────────────────────────
  'office-spaces-01-hd': { id: 'office-spaces-01-hd', category: 'office-spaces', index: 1,  title: 'Office Space #1',  r2File: 'office-spaces-01-hd.png' },
  'office-spaces-02-hd': { id: 'office-spaces-02-hd', category: 'office-spaces', index: 2,  title: 'Office Space #2',  r2File: 'office-spaces-02-hd.png' },
  'office-spaces-08-hd': { id: 'office-spaces-08-hd', category: 'office-spaces', index: 8,  title: 'Office Space #8',  r2File: 'office-spaces-08-hd.png' },
  'office-spaces-19-hd': { id: 'office-spaces-19-hd', category: 'office-spaces', index: 19, title: 'Office Space #19', r2File: 'office-spaces-19-hd.png' },
  'office-spaces-20-hd': { id: 'office-spaces-20-hd', category: 'office-spaces', index: 20, title: 'Office Space #20', r2File: 'office-spaces-20-hd.png' },
  'office-spaces-28-hd': { id: 'office-spaces-28-hd', category: 'office-spaces', index: 28, title: 'Office Space #28', r2File: 'office-spaces-28-hd.png' },
  'office-spaces-33-hd': { id: 'office-spaces-33-hd', category: 'office-spaces', index: 33, title: 'Office Space #33', r2File: 'office-spaces-33-hd.png' },
  'office-spaces-35-hd': { id: 'office-spaces-35-hd', category: 'office-spaces', index: 35, title: 'Office Space #35', r2File: 'office-spaces-35-hd.png' },
  'office-spaces-36-hd': { id: 'office-spaces-36-hd', category: 'office-spaces', index: 36, title: 'Office Space #36', r2File: 'office-spaces-36-hd.png' },
  'office-spaces-38-hd': { id: 'office-spaces-38-hd', category: 'office-spaces', index: 38, title: 'Office Space #38', r2File: 'office-spaces-38-hd.png' },
  'office-spaces-43-hd': { id: 'office-spaces-43-hd', category: 'office-spaces', index: 43, title: 'Office Space #43', r2File: 'office-spaces-43-hd.png' },
  'office-spaces-59-hd': { id: 'office-spaces-59-hd', category: 'office-spaces', index: 59, title: 'Office Space #59', r2File: 'office-spaces-59-hd.png' },
  'office-spaces-62-hd': { id: 'office-spaces-62-hd', category: 'office-spaces', index: 62, title: 'Office Space #62', r2File: 'office-spaces-62-hd.png' },
  'office-spaces-63-hd': { id: 'office-spaces-63-hd', category: 'office-spaces', index: 63, title: 'Office Space #63', r2File: 'office-spaces-63-hd.png' },
  'office-spaces-66-hd': { id: 'office-spaces-66-hd', category: 'office-spaces', index: 66, title: 'Office Space #66', r2File: 'office-spaces-66-hd.png' },
  'office-spaces-69-hd': { id: 'office-spaces-69-hd', category: 'office-spaces', index: 69, title: 'Office Space #69', r2File: 'office-spaces-69-hd.png' },
  'office-spaces-70-hd': { id: 'office-spaces-70-hd', category: 'office-spaces', index: 70, title: 'Office Space #70', r2File: 'office-spaces-70-hd.png' },
  'office-spaces-71-hd': { id: 'office-spaces-71-hd', category: 'office-spaces', index: 71, title: 'Office Space #71', r2File: 'office-spaces-71-hd.png' },
  'office-spaces-77-hd': { id: 'office-spaces-77-hd', category: 'office-spaces', index: 77, title: 'Office Space #77', r2File: 'office-spaces-77-hd.png' },
  'office-spaces-84-hd': { id: 'office-spaces-84-hd', category: 'office-spaces', index: 84, title: 'Office Space #84', r2File: 'office-spaces-84-hd.png' },
  // ── Home Offices ──────────────────────────────────────────────────────────
  'home-offices-01-hd': { id: 'home-offices-01-hd', category: 'home-office', index: 1,  title: 'Home Office #1',  r2File: 'home-offices-01-hd.png' },
  'home-offices-03-hd': { id: 'home-offices-03-hd', category: 'home-office', index: 3,  title: 'Home Office #3',  r2File: 'home-offices-03-hd.png' },
  'home-offices-04-hd': { id: 'home-offices-04-hd', category: 'home-office', index: 4,  title: 'Home Office #4',  r2File: 'home-offices-04-hd.png' },
  'home-offices-05-hd': { id: 'home-offices-05-hd', category: 'home-office', index: 5,  title: 'Home Office #5',  r2File: 'home-offices-05-hd.png' },
  'home-offices-07-hd': { id: 'home-offices-07-hd', category: 'home-office', index: 7,  title: 'Home Office #7',  r2File: 'home-offices-07-hd.png' },
  'home-offices-08-hd': { id: 'home-offices-08-hd', category: 'home-office', index: 8,  title: 'Home Office #8',  r2File: 'home-offices-08-hd.png' },
  'home-offices-13-hd': { id: 'home-offices-13-hd', category: 'home-office', index: 13, title: 'Home Office #13', r2File: 'home-offices-13-hd.png' },
  'home-offices-14-hd': { id: 'home-offices-14-hd', category: 'home-office', index: 14, title: 'Home Office #14', r2File: 'home-offices-14-hd.png' },
  'home-offices-17-hd': { id: 'home-offices-17-hd', category: 'home-office', index: 17, title: 'Home Office #17', r2File: 'home-offices-17-hd.png' },
  'home-offices-20-hd': { id: 'home-offices-20-hd', category: 'home-office', index: 20, title: 'Home Office #20', r2File: 'home-offices-20-hd.png' },
  'home-offices-22-hd': { id: 'home-offices-22-hd', category: 'home-office', index: 22, title: 'Home Office #22', r2File: 'home-offices-22-hd.png' },
  'home-offices-23-hd': { id: 'home-offices-23-hd', category: 'home-office', index: 23, title: 'Home Office #23', r2File: 'home-offices-23-hd.png' },
  'home-offices-28-hd': { id: 'home-offices-28-hd', category: 'home-office', index: 28, title: 'Home Office #28', r2File: 'home-offices-28-hd.png' },
  'home-offices-29-hd': { id: 'home-offices-29-hd', category: 'home-office', index: 29, title: 'Home Office #29', r2File: 'home-offices-29-hd.png' },
  'home-offices-30-hd': { id: 'home-offices-30-hd', category: 'home-office', index: 30, title: 'Home Office #30', r2File: 'home-offices-30-hd.png' },
  'home-offices-31-hd': { id: 'home-offices-31-hd', category: 'home-office', index: 31, title: 'Home Office #31', r2File: 'home-offices-31-hd.png' },
  'home-offices-48-hd': { id: 'home-offices-48-hd', category: 'home-office', index: 48, title: 'Home Office #48', r2File: 'home-offices-48-hd.png' },
  'home-offices-50-hd': { id: 'home-offices-50-hd', category: 'home-office', index: 50, title: 'Home Office #50', r2File: 'home-offices-50-hd.png' },
  'home-offices-62-hd': { id: 'home-offices-62-hd', category: 'home-office', index: 62, title: 'Home Office #62', r2File: 'home-offices-62-hd.png' },
  'home-offices-61-hd': { id: 'home-offices-61-hd', category: 'home-office', index: 61, title: 'Home Office #61', r2File: 'home-offices-61-hd.png' },
  'home-offices-69-hd': { id: 'home-offices-69-hd', category: 'home-office', index: 69, title: 'Home Office #69', r2File: 'home-offices-69-hd.png' },
  'home-offices-74-hd': { id: 'home-offices-74-hd', category: 'home-office', index: 74, title: 'Home Office #74', r2File: 'home-offices-74-hd.png' },
  // ── Nature Landscapes ─────────────────────────────────────────────────────
  'nature-landscape-10-hd': { id: 'nature-landscape-10-hd', category: 'nature-landscapes', index: 10, title: 'Nature Landscape #10', r2File: 'nature-landscape-10-hd.png' },
  'nature-landscape-11-hd': { id: 'nature-landscape-11-hd', category: 'nature-landscapes', index: 11, title: 'Nature Landscape #11', r2File: 'nature-landscape-11-hd.png' },
  'nature-landscape-14-hd': { id: 'nature-landscape-14-hd', category: 'nature-landscapes', index: 14, title: 'Nature Landscape #14', r2File: 'nature-landscape-14-hd.png' },
  'nature-landscape-18-hd': { id: 'nature-landscape-18-hd', category: 'nature-landscapes', index: 18, title: 'Nature Landscape #18', r2File: 'nature-landscape-18-hd.png' },
  'nature-landscape-19-hd': { id: 'nature-landscape-19-hd', category: 'nature-landscapes', index: 19, title: 'Nature Landscape #19', r2File: 'nature-landscape-19-hd.png' },
  'nature-landscape-20-hd': { id: 'nature-landscape-20-hd', category: 'nature-landscapes', index: 20, title: 'Nature Landscape #20', r2File: 'nature-landscape-20-hd.png' },
  'nature-landscape-21-hd': { id: 'nature-landscape-21-hd', category: 'nature-landscapes', index: 21, title: 'Nature Landscape #21', r2File: 'nature-landscape-21-hd.png' },
  'nature-landscape-22-hd': { id: 'nature-landscape-22-hd', category: 'nature-landscapes', index: 22, title: 'Nature Landscape #22', r2File: 'nature-landscape-22-hd.png' },
  'nature-landscape-30-hd': { id: 'nature-landscape-30-hd', category: 'nature-landscapes', index: 30, title: 'Nature Landscape #30', r2File: 'nature-landscape-30-hd.png' },
  'nature-landscape-46-hd': { id: 'nature-landscape-46-hd', category: 'nature-landscapes', index: 46, title: 'Nature Landscape #46', r2File: 'nature-landscape-46-hd.png' },
  'nature-landscape-98-hd': { id: 'nature-landscape-98-hd', category: 'nature-landscapes', index: 98, title: 'Nature Landscape #98', r2File: 'nature-landscape-98-hd.png' },
  'nature-landscape-99-hd': { id: 'nature-landscape-99-hd', category: 'nature-landscapes', index: 99, title: 'Nature Landscape #99', r2File: 'nature-landscape-99-hd.png' },
  // ── Living Rooms ──────────────────────────────────────────────────────────
  'living-room-08-hd': { id: 'living-room-08-hd', category: 'living-rooms', index: 8,  title: 'Living Room #8',  r2File: 'living-room-08-hd.png' },
  'living-room-10-hd': { id: 'living-room-10-hd', category: 'living-rooms', index: 10, title: 'Living Room #10', r2File: 'living-room-10-hd.png' },
  'living-room-11-hd': { id: 'living-room-11-hd', category: 'living-rooms', index: 11, title: 'Living Room #11', r2File: 'living-room-11-hd.png' },
  'living-room-14-hd': { id: 'living-room-14-hd', category: 'living-rooms', index: 14, title: 'Living Room #14', r2File: 'living-room-14-hd.png' },
  'living-room-17-hd': { id: 'living-room-17-hd', category: 'living-rooms', index: 17, title: 'Living Room #17', r2File: 'living-room-17-hd.png' },
  'living-room-27-hd': { id: 'living-room-27-hd', category: 'living-rooms', index: 27, title: 'Living Room #27', r2File: 'living-room-27-hd.png' },
  'living-room-41-hd': { id: 'living-room-41-hd', category: 'living-rooms', index: 41, title: 'Living Room #41', r2File: 'living-room-41-hd.png' },
  'living-room-46-hd': { id: 'living-room-46-hd', category: 'living-rooms', index: 46, title: 'Living Room #46', r2File: 'living-room-46-hd.png' },
  // ── Kitchens ──────────────────────────────────────────────────────────────
  'kitchen-04-hd': { id: 'kitchen-04-hd', category: 'kitchens', index: 4,  title: 'Kitchen #4',  r2File: 'kitchen-04-hd.png' },
  'kitchen-05-hd': { id: 'kitchen-05-hd', category: 'kitchens', index: 5,  title: 'Kitchen #5',  r2File: 'kitchen-05-hd.png' },
  'kitchen-06-hd': { id: 'kitchen-06-hd', category: 'kitchens', index: 6,  title: 'Kitchen #6',  r2File: 'kitchen-06-hd.png' },
  'kitchen-14-hd': { id: 'kitchen-14-hd', category: 'kitchens', index: 14, title: 'Kitchen #14', r2File: 'kitchen-14-hd.png' },
  'kitchen-15-hd': { id: 'kitchen-15-hd', category: 'kitchens', index: 15, title: 'Kitchen #15', r2File: 'kitchen-15-hd.png' },
  'kitchen-16-hd': { id: 'kitchen-16-hd', category: 'kitchens', index: 16, title: 'Kitchen #16', r2File: 'kitchen-16-hd.png' },
  // ── Gardens & Patios ──────────────────────────────────────────────────────
  'garden-patio-01-hd': { id: 'garden-patio-01-hd', category: 'gardens-patios', index: 1,  title: 'Garden & Patio #1',  r2File: 'garden-patio-01-hd.png' },
  'garden-patio-12-hd': { id: 'garden-patio-12-hd', category: 'gardens-patios', index: 12, title: 'Garden & Patio #12', r2File: 'garden-patio-12-hd.png' },
  'garden-patio-14-hd': { id: 'garden-patio-14-hd', category: 'gardens-patios', index: 14, title: 'Garden & Patio #14', r2File: 'garden-patio-14-hd.png' },
  // ── Christmas ─────────────────────────────────────────────────────────────
  'christmas-background-35-hd': { id: 'christmas-background-35-hd', category: 'christmas-backgrounds', index: 35, title: 'Christmas #35', r2File: 'christmas-background-35-hd.png' },
  // ── Easter ────────────────────────────────────────────────────────────────
  'easter-background-03-hd':  { id: 'easter-background-03-hd',  category: 'easter-backgrounds', index: 3,   title: 'Easter #3',   r2File: 'easter-background-03-hd.png' },
  'easter-background-04-hd':  { id: 'easter-background-04-hd',  category: 'easter-backgrounds', index: 4,   title: 'Easter #4',   r2File: 'easter-background-04-hd.png' },
  'easter-background-21-hd':  { id: 'easter-background-21-hd',  category: 'easter-backgrounds', index: 21,  title: 'Easter #21',  r2File: 'easter-background-21-hd.png' },
  'easter-background-32-hd':  { id: 'easter-background-32-hd',  category: 'easter-backgrounds', index: 32,  title: 'Easter #32',  r2File: 'easter-background-32-hd.png' },
  'easter-background-35-hd':  { id: 'easter-background-35-hd',  category: 'easter-backgrounds', index: 35,  title: 'Easter #35',  r2File: 'easter-background-35-hd.png' },
  'easter-background-39-hd':  { id: 'easter-background-39-hd',  category: 'easter-backgrounds', index: 39,  title: 'Easter #39',  r2File: 'easter-background-39-hd.png' },
  'easter-background-42-hd':  { id: 'easter-background-42-hd',  category: 'easter-backgrounds', index: 42,  title: 'Easter #42',  r2File: 'easter-background-42-hd.png' },
  'easter-background-48-hd':  { id: 'easter-background-48-hd',  category: 'easter-backgrounds', index: 48,  title: 'Easter #48',  r2File: 'easter-background-48-hd.png' },
  'easter-background-49-hd':  { id: 'easter-background-49-hd',  category: 'easter-backgrounds', index: 49,  title: 'Easter #49',  r2File: 'easter-background-49-hd.png' },
  'easter-background-56-hd':  { id: 'easter-background-56-hd',  category: 'easter-backgrounds', index: 56,  title: 'Easter #56',  r2File: 'easter-background-56-hd.png' },
  'easter-background-57-hd':  { id: 'easter-background-57-hd',  category: 'easter-backgrounds', index: 57,  title: 'Easter #57',  r2File: 'easter-background-57-hd.png' },
  'easter-background-61-hd':  { id: 'easter-background-61-hd',  category: 'easter-backgrounds', index: 61,  title: 'Easter #61',  r2File: 'easter-background-61-hd.png' },
  'easter-background-66-hd':  { id: 'easter-background-66-hd',  category: 'easter-backgrounds', index: 66,  title: 'Easter #66',  r2File: 'easter-background-66-hd.png' },
  'easter-background-72-hd':  { id: 'easter-background-72-hd',  category: 'easter-backgrounds', index: 72,  title: 'Easter #72',  r2File: 'easter-background-72-hd.png' },
  'easter-background-74-hd':  { id: 'easter-background-74-hd',  category: 'easter-backgrounds', index: 74,  title: 'Easter #74',  r2File: 'easter-background-74-hd.png' },
  'easter-background-75-hd':  { id: 'easter-background-75-hd',  category: 'easter-backgrounds', index: 75,  title: 'Easter #75',  r2File: 'easter-background-75-hd.png' },
  'easter-background-88-hd':  { id: 'easter-background-88-hd',  category: 'easter-backgrounds', index: 88,  title: 'Easter #88',  r2File: 'easter-background-88-hd.png' },
  'easter-background-91-hd':  { id: 'easter-background-91-hd',  category: 'easter-backgrounds', index: 91,  title: 'Easter #91',  r2File: 'easter-background-91-hd.png' },
  'easter-background-92-hd':  { id: 'easter-background-92-hd',  category: 'easter-backgrounds', index: 92,  title: 'Easter #92',  r2File: 'easter-background-92-hd.png' },
  'easter-background-93-hd':  { id: 'easter-background-93-hd',  category: 'easter-backgrounds', index: 93,  title: 'Easter #93',  r2File: 'easter-background-93-hd.png' },
  'easter-background-99-hd':  { id: 'easter-background-99-hd',  category: 'easter-backgrounds', index: 99,  title: 'Easter #99',  r2File: 'easter-background-99-hd.png' },
  'easter-background-101-hd': { id: 'easter-background-101-hd', category: 'easter-backgrounds', index: 101, title: 'Easter #101', r2File: 'easter-background-101-hd.png' },
  // ── Spring ────────────────────────────────────────────────────────────────
  'spring-background-01-hd': { id: 'spring-background-01-hd', category: 'spring-backgrounds', index: 1,  title: 'Spring #1',  r2File: 'spring-background-01-hd.png' },
  'spring-background-36-hd': { id: 'spring-background-36-hd', category: 'spring-backgrounds', index: 36, title: 'Spring #36', r2File: 'spring-background-36-hd.png' },
  'spring-background-55-hd': { id: 'spring-background-55-hd', category: 'spring-backgrounds', index: 55, title: 'Spring #55', r2File: 'spring-background-55-hd.png' },
  'spring-background-63-hd': { id: 'spring-background-63-hd', category: 'spring-backgrounds', index: 63, title: 'Spring #63', r2File: 'spring-background-63-hd.png' },
  'spring-background-73-hd': { id: 'spring-background-73-hd', category: 'spring-backgrounds', index: 73, title: 'Spring #73', r2File: 'spring-background-73-hd.png' },
  'spring-background-74-hd': { id: 'spring-background-74-hd', category: 'spring-backgrounds', index: 74, title: 'Spring #74', r2File: 'spring-background-74-hd.png' },
};

/** Returns the product for a given productId, or null if not found. */
export function getProduct(productId) {
  return PRODUCTS[productId] ?? null;
}
